version: '3.8'

services:
  project_management_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: project_management_api-image
    container_name: project_management_api-container
    restart: always
    volumes:
      - /var/www/project_management_api/static:/usr/src/app/static
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      APP_PORT: ${APP_PORT}
      ENVIRONMENT: ${ENVIRONMENT}
      EXPIRES_IN: ${EXPIRES_IN}
      SECRET_PRIVATE_KEY: ${SECRET_PRIVATE_KEY}
      TZ: ${CONTAINER_TZ}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE}