global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'mariadb-exporter'
    static_configs:
      - targets: ['mariadb_exporter:9104']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'mssql-exporter'
    static_configs:
      - targets: ['mssql_exporter:9214']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nest-ingest'
    static_configs:
      - targets: ['nest:4000']
    metrics_path: '/metrics'