{
 "title": "DB Ingestion - NestJS",
 "tags": [
  "ingestion",
  "nest"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "P95 Ingestion Latency by DB and Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ingest_latency_ms_bucket[1m])) by (le,db,method))"
    }
   ]
  },
  {
   "title": "Rows Ingested per Second by DB and Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(ingest_rows_total[1m])) by (db,method)"
    }
   ]
  },
  {
   "title": "Inflight Writes by DB and Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ingest_inflight_writes) by (db,method)"
    }
   ]
  },
  {
   "title": "Ingestion Failures per Second by DB and Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(ingest_failures_total[1m])) by (db,method)"
    }
   ]
  }
 ]
}